"""报告保存 + 终端预览 + HTML 导出"""

import os
import re
from datetime import datetime


def save_report(report: str, app_name: str, output_dir: str = "reports") -> str:
    """保存报告到 Markdown 文件，返回文件路径"""
    os.makedirs(output_dir, exist_ok=True)
    date_str = datetime.now().strftime("%Y%m%d")
    filename = f"{app_name}-评论洞察-{date_str}.md"
    filepath = os.path.join(output_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    return filepath


def markdown_to_html(md_text: str) -> str:
    """将 Markdown 转为 HTML（轻量实现，不依赖外部库）"""
    html = md_text

    # 转义 HTML 特殊字符（保留已有的 HTML 标签）
    # 先处理代码块，避免内部被转义
    code_blocks = []
    def _save_code(m):
        code_blocks.append(m.group(1))
        return f"__CODE_BLOCK_{len(code_blocks) - 1}__"
    html = re.sub(r'```[\w]*\n(.*?)```', _save_code, html, flags=re.DOTALL)

    # 标题
    html = re.sub(r'^##### (.+)$', r'<h5>\1</h5>', html, flags=re.MULTILINE)
    html = re.sub(r'^#### (.+)$', r'<h4>\1</h4>', html, flags=re.MULTILINE)
    html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
    html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
    html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)

    # 粗体和斜体
    html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
    html = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html)

    # 引用
    html = re.sub(r'^> (.+)$', r'<blockquote>\1</blockquote>', html, flags=re.MULTILINE)

    # 水平线
    html = re.sub(r'^---+$', r'<hr>', html, flags=re.MULTILINE)

    # 表格
    lines = html.split('\n')
    in_table = False
    table_lines = []
    result_lines = []
    for line in lines:
        stripped = line.strip()
        if '|' in stripped and stripped.startswith('|') and stripped.endswith('|'):
            if re.match(r'^\|[\s\-:|]+\|$', stripped):
                # 分隔行，跳过
                continue
            cells = [c.strip() for c in stripped.split('|')[1:-1]]
            if not in_table:
                in_table = True
                result_lines.append('<table>')
                result_lines.append('<thead><tr>' + ''.join(f'<th>{c}</th>' for c in cells) + '</tr></thead>')
                result_lines.append('<tbody>')
            else:
                result_lines.append('<tr>' + ''.join(f'<td>{c}</td>' for c in cells) + '</tr>')
        else:
            if in_table:
                result_lines.append('</tbody></table>')
                in_table = False
            result_lines.append(line)
    if in_table:
        result_lines.append('</tbody></table>')
    html = '\n'.join(result_lines)

    # 恢复代码块
    for i, code in enumerate(code_blocks):
        html = html.replace(f"__CODE_BLOCK_{i}__", f'<pre><code>{code}</code></pre>')

    # 段落（连续非空行包裹为 <p>）
    html = re.sub(r'\n{2,}', '\n\n', html)
    paragraphs = html.split('\n\n')
    processed = []
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
        if p.startswith('<'):
            processed.append(p)
        else:
            processed.append(f'<p>{p}</p>')
    html = '\n'.join(processed)

    return html


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px 20px;
    color: #1E1E2E;
    background: #FFFFFF;
    line-height: 1.7;
  }}
  h1 {{ font-size: 2em; font-weight: 700; margin-top: 2em; border-bottom: 2px solid #E5E7EB; padding-bottom: 8px; }}
  h2 {{ font-size: 1.5em; font-weight: 600; margin-top: 1.8em; border-bottom: 1px solid #E5E7EB; padding-bottom: 6px; }}
  h3 {{ font-size: 1.25em; font-weight: 600; margin-top: 1.5em; }}
  h4 {{ font-size: 1.1em; font-weight: 600; margin-top: 1.2em; }}
  p {{ margin: 0.8em 0; }}
  blockquote {{
    border-left: 3px solid #E5E7EB;
    padding: 4px 16px;
    margin: 12px 0;
    color: #6B7280;
    background: #F8F7FF;
    border-radius: 0 4px 4px 0;
  }}
  table {{
    border-collapse: collapse;
    width: 100%;
    margin: 16px 0;
    font-size: 0.9em;
  }}
  th, td {{
    border: 1px solid #E5E7EB;
    padding: 8px 12px;
    text-align: left;
  }}
  th {{
    background: #F8F7FF;
    font-weight: 600;
  }}
  tr:nth-child(even) {{ background: #FAFAFA; }}
  hr {{ border: none; border-top: 1px solid #E5E7EB; margin: 2em 0; }}
  strong {{ font-weight: 600; }}
  pre {{
    background: #F8F7FF;
    padding: 12px 16px;
    border-radius: 4px;
    overflow-x: auto;
    font-size: 0.85em;
  }}
  code {{ font-family: "SF Mono", Monaco, Consolas, monospace; }}
  .footer {{
    margin-top: 3em;
    padding-top: 1em;
    border-top: 1px solid #E5E7EB;
    color: #6B7280;
    font-size: 0.85em;
    text-align: center;
  }}
</style>
</head>
<body>
{content}
<div class="footer">
  Generated by AppPulse &middot; {date}
</div>
</body>
</html>"""


def generate_html_report(report_md: str, app_name: str) -> str:
    """将 Markdown 报告转为完整的 HTML 页面"""
    html_content = markdown_to_html(report_md)
    title = f"{app_name} - 用户评论洞察报告"
    date = datetime.now().strftime("%Y-%m-%d")
    return _HTML_TEMPLATE.format(
        title=title,
        content=html_content,
        date=date,
    )
